# Generated by Django 5.2.1 on 2025-05-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_conge_options_alter_employer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to='gestion.employer', verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='conge',
            name='commentaire_approbation',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire d'approbation"),
        ),
    ]
